executable = thejob_2018B_cmsdas.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ""
transfer_output_files = ""
arguments = "scout_$(ProcId).root /afs/cern.ch/user/f/fmokhtar/CMSDASMuonScouting/CMSSW_10_1_6/src/DarkPhotonAnalysisV2/DimuonAnalysis/macros/"
universe = vanilla
queue 265
+JobFlavour = "longlunch"



# or
# queue INPUT in (
# file1
# file2
# file3
# ..
# )
